### ISSUE TITLE
[request]: Support IRSA provided AWS credentials on EKS in envoy proxy

### ISSUE THREAD

**Issue by dagvl** [aws/aws-app-mesh-roadmap#102]
**Tell us about your request**
The EKS team just released their solution for providing pods with IAM credentials: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

From what I can see, the envoy proxy does not seem to support this yet. It would be great if it did so we can use the same method of injecting credentials in all our pods.

**Which integration(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to manage pod credentials in the same way for all our EKS services using best practices. As the credentials are shared pr pod and the envoy proxy sidecar becomes part of our service pod, it should also support getting credentials through this best practice. 

There is a possible work-around where the envoy proxy would relay on the instance role instead of pod-supplied credentials. Currently this is hard for us because we use kiam and kiam implements a annotation on a pr pod basis that would override the IRSA provided credentials, blocking a "incremental deployement" scenario. We would have to remove kiam totally for this to work and that becomes a hard to manage "everybody must change at the same time" scenario for bigger clusters.

**Comment by kiranmeduri** [comment]
@nckturner any ideas on how we can expedite this? Seems like a easy enough fix under aws-app-mesh-inject

**Comment by kiranmeduri** [comment]
@dagvl now I understand what you meant by envoy proxy not supporting IRSA. Envoy proxy uses AWS credentials to connect to App Mesh xDS endpoint, to support IAM roles via EC2 or ECS it uses [credentials_provider](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/common/aws/credentials_provider_impl.cc). However, this does not support [STSCredentials](https://github.com/aws/aws-sdk-cpp/blob/75ef87fcd353c561f42de7c3a6685e57c889592b/aws-cpp-sdk-core/source/auth/STSCredentialsProvider.cpp). Kubernetes IRSA uses STS credentials path that needs to be added to Envoy proxy. On a side-note it may be better to use aws-cpp-sdk instead of custom credentials provider implementation. @lavignes can you comment on this. 

Once that is done, I believe a pod-spec with service-account (IRSA) will just work. @dagvl correct me if there any other missing things.

Thanks

**Comment by nckturner** [comment]
> However, this does not support STSCredentials.

Why doesn't envoy support `sts:AssumeRoleWithWebIdentity`?  Do I understand correctly that you're not using the CPP SDK in the current implementation?  I'm guessing its to avoid bloat, but I'd be interested what the savings are.  

In any case, you are correct that if it supports `sts:AssumeRoleWithWebIdentity` then IRSA will just work.

**Comment by lavignes** [comment]
@nckturner No, Envoy currently does not use the CPP SDK. Bloat was not really the reason as much as the dependencies that the SDK brings in and how they interact or potentially run counter to initiatives within the Envoy codebase. When I originally added support for Envoy to talk to AppMesh I added the CPP SDK, but it was a fairly hacky and could not easily be turned off using Envoy's extension system. This caused certain features like hot-restart, OpenCensus tracing, and Windows (and macOS support I believe) to no longer build in that version. it seemed more attractive at the time to just leverage Envoys internal APIs to reimplement creds fetching and signing.

Particularly, the cURL and OpenSSL dependencies that the core CPP SDK uses were the ones that were difficult to replace with Envoys own HTTP client and crypto. The CPP SDK needs to initialize a bunch of global state in cURL and OpenSSL once at app startup and that didn't fit well into Envoy at the time.

Envoy has since begun moving to a more modular design that would make it easier to model the CPP SDK as an extension that can be disabled if the extensions that don't use it aren't being used themselves. To @kiranmeduri 's point, it may make sense to just migrate back now.

On the other hand, I have looked into adding an STS Credentials provider to Envoy, and it doesn't seem too difficult (~100 LOC got me a somewhat working version locally). I'll need to talk more with the team on the approach to get this done.

**Comment by lavignes** [comment]
@dagvl FYI. We've just released an updated Envoy image with IRSA support: #137

**Comment by dagvl** [comment]
@lavignes, that's great news, thanks!

**Comment by lavignes** [comment]
For anyone else watching this issue. We've released a new [Envoy image](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html) that supports fetching credentials via IRSA.

Which at the time of this writing is:
```
840364872350.dkr.ecr.<region>.amazonaws.com/aws-appmesh-envoy:v1.12.1.1-prod
```

So we should be good to resolve this issue. Thanks all!
