### ISSUE TITLE
Service limits

### ISSUE THREAD

**Issue by sviik** [aws/aws-app-mesh-roadmap#109]
https://docs.aws.amazon.com/app-mesh/latest/userguide/service_limits.html

`AWS App Mesh Service Limits` table shows that the default limit for maximum number of virtual nodes and virtual routers **per mesh** is 20. Should that be **per virtual service** instead? Asking because the limit for virtual services is 200 per mesh, and one would expect to have at least same amount of virtual nodes/routers.

**Comment by shubharao** [comment]
"@sviik Thanks for the feedback on this. We understand that the current limits don’t meet all of our customers needs. We are working on increasing the limits (see: https://github.com/aws/aws-app-mesh-roadmap/issues/110) and it is coming soon. For the short term, you can email us at aws-appmesh-feedback@amazon.com with your account details and we are happy to increase.

We set the limits for Virtual Services higher because when we were in pre-GA preview we modeled every backend as a virtual service. Post GA, we left it at that because our intent is to raise all service limits this year.

**Comment by sviik** [comment]
This makes sense, thanks!
