### ISSUE TITLE
Feature Request: Routing to multiple TCP destinations on the same port

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#195]
**Tell us about your request**
I would like to be able to route traffic to multiple backends which have been modeled as TCP (via the [PortMapping setting](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_PortMapping.html)) via the same port.

For example, I may wish to model several external services as TCP Virtual Nodes on port 443 to allow TLS connectivity to those services easily within App Mesh.

**Which integration(s) is this request for?**
All

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today, it is not possible to route to multiple backend destinations on a given Virtual Node which use TCP as the protocol and share the same port. This is due to limitations of routing TCP traffic (for which only the source and destination IP and port are known).

**Are you currently working around this issue?**
To work around the issue, you can use a Virtual Router with a different port per backend to disambiguate the routing logic, while leaving the Virtual Node port as 443 for example.

**Additional context**
With TCP and TLS, Server Name Indicator (SNI) could be used to disambiguate traffic routing. DNS proxying by Envoy (envoyproxy/envoy#6748) could also be used, since the proxy would be the authoritative DNS resolver for destinations modeled in App Mesh, regardless of TLS.

**Comment by nsheaps** [comment]
The docs suggest that HTTPS services should be modeled as TCP services. We attempted to do this with a service not in our mesh who's destination was TLS enabled on port 443 not knowing that this issue existed. 

We've since synced with AWS support on this and they shared this workaround. We also shared another work around with them where the service is modeled as an HTTP service and the virtual node's TLS mode is set to `STRICT` where it upgrades to HTTPS at envoy. This also enables us to utilize envoy for retry policies on HTTPS services.

This would be desired to us and seems achievable by adding the virtual service to the server name indicator similarly to how the cluster discovery service adds `*.amazonaws.com` to it's filter match for routing egress traffic to 443.

**Comment by vishnuvisnu** [comment]
@nsheaps could you please share more details on the work around you are using? Did you have to change the envoy config file to achieve but cluster discovery service adds *.amazonaws.com to its filter match?

@bcelenza The workaround you have suggested in the issue, does this require changing end points (changing port numbers) at the client side?

**Comment by recreational-snacker** [comment]
@herrhound is there any feedback on the status of this feature? We have a large client in the process of migrating to AWS using App Mesh and we've run into this same problem, hoping there will be a resolution to this?

**Comment by rajal-amzn** [comment]
@vishnuvisnu The workaround for this issue is to declare a VirtualRouter for the VirtualService with the destination TCP service name (lets say x.com) and add a port to the VirtualRouter which is unique (say, 444) and from the client, you would need to change the port to the VirtualRouter port (444 in this case). The request would be forwarded to the actual VirtualNode port of the destination service (say, 443) and you do not need to modify the envoy config manually.

**Comment by flashyang** [comment]
Also please look at our [trouble shooting doc]( https://docs.aws.amazon.com/app-mesh/latest/userguide/troubleshooting-connectivity.html) for the workaround of this issue, you can find the workaround in the `Unable to connect to a service modeled as a TCP virtual node or virtual router in App Mesh ` section

**Comment by visit1985** [comment]
> @vishnuvisnu The workaround for this issue is to declare a VirtualRouter for the VirtualService with the destination TCP service name (lets say `x.com`) and add a port to the VirtualRouter which is unique (say, `444`) and from the client, you would need to change the port to the VirtualRouter port (`444` in this case). The request would be forwarded to the actual VirtualNode port of the destination service (say, `443`) and you do not need to modify the envoy config manually.

I would like to point out, that this workaround still requires HTTP header manipulation on client side. Client apps would set the host header to `x.com:444` by default, which will result in HTTP 404 for strict SNI/vHost configurations on the destination side.
