### ISSUE TITLE
Unable to attach the EFS volume with ECS service while integrating with App Mesh.

### ISSUE THREAD

**Issue by atreyd** [aws/aws-app-mesh-roadmap#220]
Hi Team,

I am working on the ECS-AppMesh integration for one of the microservices. The microservice uses the configurations files from EFS volume and I am able to run the microservice in the ECS cluster in AWSVPC and Bridge network mode successfully.

But when I am trying to integrate the appmesh proxy configuration with Envoy and X-ray as a sidecar containers in the service then the tasks are not getting deployed with the below issue.

`Stopped reason: Error response from daemon: create ecs-xxx-service-9-EFS-xxxxxxxxxxx4f00: VolumeDriver.Create: mounting volume failed: mount.nfs4: Connection reset by peer`

As I mentioned above, I am able to run the containers in the same service without the AppMesh integration.

Initially, I suspect if the Envoy container also needs access to the EFS volume but then it didn't work even after providing the mount point to the Envoy container.

How can Envoy proxy block the connection between EFS and app container ?

**Comment by dastbe** [comment]
Thanks for the bug report. We'll check with the ECS team to better understand the network model for EFS and see what needs to be documented or changed here.

**Comment by dastbe** [comment]
After discussing with our resident EFS expert, our understanding is that EFS secures communication between client and server by setting up a TLS tunnel to EFS on port 2049. Within your task, the NFS client talks to localhost:<arbitrary-port> which then proxies communication over that tunnel. With App Mesh enabled, that TLS tunnel is unable to be instantiated which results in the error you see.

Given Envoy is not running when this connection occurs, the only solution we have here is to ignore the port in [EgressIgnoredPorts on the Proxy Configuration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html). 

I'm going to test this explicitly to confirm, but wanted to alert you to what we think the fix is.

**Comment by atreyd** [comment]
@dastbe I was able to get it working after adding the EFS port under EgressIgnoredPort in Envoy configuration. But I agree with  you on the documentation part that it should be a part of one of the troubleshooting issues.
Thanks for the pointers.

**Comment by dastbe** [comment]
We've updated our docs here: https://docs.aws.amazon.com/app-mesh/latest/userguide/troubleshoot-connectivity.html#ts-connectivity-efs

I've created a feature request for automatic configuration at #228
