### ISSUE TITLE
Feature Request: Better error handling for misconfigured/typed ENV in /usr/bin/envoy-wrapper

### ISSUE THREAD

**Issue by tobypinder** [aws/aws-app-mesh-roadmap#243]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
While integrating the AWS specific `envoy` sidecars in our ECS cluster we had set `ENABLE_ENVOY_DOG_STATSD` to `true` as part of the `proxy_container` task definition block. Unbeknownst to us this was the source of a logging error that would appear on container startup of 

```sh
/usr/bin/envoy-wrapper: line 108: [: true: integer expression expected
```

as the `envoy-wrapper` shell script performs an `if [ "$ENABLE_ENVOY_DOG_STATSD" -eq 1 ]; then` check on that line (after having initialised the value to `0` if it was unset.

**Which integration(s) is this request for?**
The envoy proxy container itself

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As a user I am trying to integrate AppMesh with ECS and would like if these type restrictions were in the [documentation](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html#envoy-dogstatsd-config) or preferably if this could be detected and warned about on startup with a more helpful error message. Given the relative opacity of this docker-entrypoint script to customers it's especially relevant, as it's not easy to read these script in (say) a github repository or other public place in which the config can be examined/diffed between releases.

**Are you currently working around this issue?**
To resolve these issues we have pulled the entrypoint script out of the container to examine the contents, modifying the structure of the env we pass as needed (In this specific case, setting `ENABLE_ENVOY_DOG_STATSD` to `1`).

**Additional context**
It seems there would be other parts of that file that do similar integer comparisons creating similar restrictions on input types for "truthiness". 

Tested with `v1.12.3.0-prod` and `v1.12.5.0-prod`, `eu-west-1` should this be relevant.

**Comment by lavignes** [comment]
Hey @tobypinder, thanks for the feedback here! I have even accidentally input `true` for some of these options before. We'll add support for any "truthy" value for these boolean variables so this is less of a landmine in the future. I also went ahead and improved the error messaging here (and some other places :sweat_smile:) to call out the environment variable name and what bad value was passed if we can't parse it.

I can't give an ETA for that change to go out since it just missed #242 but it should hopefully be included in the next minor release of the image.

As far as the other points:
* Making this code easily accessible / open-source. I think it is worthwhile and can help people debug issues they might run into. It sounds tangential to #5. This is a good use-case.
* Documentation. Ill try and get the docs updated ASAP to make this more clear.

**Comment by tobypinder** [comment]
Thank you very much for the speedy response, and glad to hear it's been addressed in future releases already! I'd agree on the further comments RE: making the image more accessible but it seems it's already in the roadmap.

Not sure on the ticket workflow in this repo but feel free to close this as resolved.

**Comment by lavignes** [comment]
We can leave this open until the docs are updated at least to show that `1` is required for the "truthy" environment variables for now.
