### ISSUE TITLE
Envoy errors not reported as X-Ray errors

### ISSUE THREAD

**Issue by mjgp2** [aws/aws-app-mesh-roadmap#344]
**Summary**
Envoy errors not reported as X-Ray errors

**Steps to Reproduce**
Stress an ingress gateway by pushing more QPS than it can handle, look at X-Ray traces - see that there is a `503` with `error: true` in annotations, but `error: false` for segment.

![image](https://user-images.githubusercontent.com/888462/118503369-7a168780-b722-11eb-8677-ad83da06b1bc.png)

**Are you currently working around this issue?**
No workaround.

**Additional context**
Totally screws up all the AWS dashboarding.

**Comment by suniltheta** [comment]
Thanks for bringing this out. This issue is fixed on envoy's X-Ray extension. We have back-ported this change onto [v1.19.1.0-prod release](https://github.com/aws/aws-app-mesh-roadmap/issues/369) of AppMesh compatible Envoy image. You can find the info about the newly released images on aws docs at https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html

**Comment by suniltheta** [comment]
Closing the issue as it is fixed. If you think the concern is not resolved yet, please feel free to re-open this issue.
