### ISSUE TITLE
mTLS with ELB and ECS setup in App Mesh

### ISSUE THREAD

**Issue by ulziibay** [aws/aws-app-mesh-roadmap#358]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**
When trying to setup mTLS within the following architecture, with 2 applications, I am finding it impossible to setup the traffic from LB2 into the Proxy for App2 to be doing mTLS. 
![aws_question_1](https://user-images.githubusercontent.com/1626382/123173853-158ecc80-d434-11eb-8047-5d292c34b6ef.png)

My question is how to enable mTLS client validation on ELB side so that I can enable "TLS Validation" on my virtual node for App 2?

If I disable "TLS Validation" on virtual node 2, then the traffic seemlessly communite TLS and I can validate the encryption is working based on https://docs.aws.amazon.com/app-mesh/latest/userguide/tls.html#verify-encryption.

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?
Very broadly
1. Setup LB 
2. Setup a virtual node that point to that LB with "TLS Validation" on
3. Query the LB DNS host directly and observe 502
4. Query a virtual node Proxy IP directly and observe 200

**Are you currently working around this issue?**
No

**Additional context**
Anything else we should know?
I found https://docs.aws.amazon.com/app-mesh/latest/userguide/troubleshooting-security.html#ts-security-tls-elb this extremely helpful. However, this is with ELB setup with only TLS enabled. It does have a troubleshooting when mTLS is enabled (aka "TLS Validation" setting ticked on the virtual node).
  
**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look.(Remember to remove any personally-identifiable information.)
![aws_question_1](https://user-images.githubusercontent.com/1626382/123173853-158ecc80-d434-11eb-8047-5d292c34b6ef.png)

**Comment by efe-selcuk** [comment]
Hi there. I'm not sure that I understand the ask here, but if it boils down to "how do I do mutual TLS between an app mesh proxy and an ALB/NLB", AFAIK it's not possible because ELB does not currently support providing client certificates.

i.e. [app] <-> [envoy] <---- (TLS works but you want this to be mutually authenticated) ----> [ALB/NLB]

That being said, I don't quite understand how the load balancers fit into the right side of that picture. Your egress traffic from the applications are going through the proxies anyway, so the more idiomatic architecture would be:

 [browser] TLS-> [ELB] TLS-> [Virtual Gateway] (TLS/mTLS)-> [Rest of the mesh with TLS/mTLS]

where "rest of the mesh is just proxy-fronted applications.

**Comment by rajal-amzn** [comment]
+1 to @efe-selcuk  If App1 and App2 are part of the same mesh, you do not need an ELB between the applications. The sidecar Envoy does the load balancing across all the available endpoints at runtime. When App1 and App2 are not part of the same mesh, you could forward the traffic from NLB to a Virtual Gateway which would validate the client cert.

**Comment by rajal-amzn** [comment]
@ulziibay We hope you questions are answered. Please re-open if you have any more queries. Resolving this for now.
