### ISSUE TITLE
Egress Configuration for Sidecars

### ISSUE THREAD

**Issue by seubert** [aws/aws-app-mesh-roadmap#44]
I have seen #76 and related issues discussing egress configuration but it's still unclear to me how to properly setup egress to something completely outside of my cluster on the internet. My scenario is running a sidecar container next to my application container and the Envoy/App Mesh container that collects metrics and pushes them to an external service. Obviously this doesn't work by default because there's no backend defined to let that traffic leave the cluster. Is this a scenario that is covered in docs or an issue that I missed?

**Comment by bcelenza** [comment]
Sorry for the delay in *my* response as well. This got lost in the shuffle to our GA launch. Looking at your logs, here's what I can make out:

**2019-03-08 20:36:20.880**: Envoy Starts
**2019-03-08 20:36:21.160**: Cluster configuration received from Envoy Management Service. Cluster warming (DNS resolution and initial health checks) begins.
... A few outbound requests are attempted here (to address 0.0.0.0:0) but fail due to no listeners or routes
**2019-03-08 20:36:21.197**: Listener configuration received from Envoy Management Service
**2019-03-08 20:36:21.210**: Route configuration received from Envoy Management Service
**2019-03-08 20:36:21.215**: Cluster warming completes. This is the point when Envoy is ready to begin handling requests.
**2019-03-08 20:36:21.526**: Outbound requests begin to succeed

So it definitely appears that the connectivity issues you're seeing early on are the result of Envoy bootstrapping. From Envoy launch to fully ready is about 1 second in total, but there are several areas in the logs where I can see requests failing until Cluster warming completes.

If you're using ECS, you can mitigate against this with the new [container dependency management](https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-ecs-introduces-enhanced-container-dependency-management/) feature by making your application and other egressing sidecars depend on the Envoy container. That will allow the Envoy to start first and become healthy before continuing with the other containers. 

We recently updated our [colorapp example](https://github.com/aws/aws-app-mesh-examples/blob/master/examples/apps/colorapp/ecs/colorgateway-base-task-def.json#L67-L71) with this setting. For the Envoy container health check, I would use the command: `curl -s http://localhost:9901/server_info | cut -d' ' -f3 | grep -q live`. This will ensure the "healthy" state of the Envoy container is when it is fully bootstrapped.

Hope this helps!

**Comment by bcelenza** [comment]
Previous command I pasted was relevant for Envoy 1.8, but not 1.9. We're updating the command for 1.9 (sorry for the confusion if this is the version you're on). https://github.com/aws/aws-app-mesh-examples/pull/115

**Comment by seubert** [comment]
thanks, that's great background and info. Going to go ahead and close this.
