### ISSUE TITLE
ECS integration with App Mesh in the ECS console

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#8]

**Comment by coultn** [comment]
With this feature, ECS and Fargate customers will be able to 
- add an existing service to App Mesh
- when creating a new service, add it to App Mesh.

The console will perform the following on behalf of the customer:
1. Inject the latest Envoy image into the task definition
2. Configure the [container start order](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_dependson) so that Envoy starts first
3. Configure the ECS [proxyConfiguration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html)

**Comment by shubharao** [comment]
This is launched! More details here: https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecs-console-enables-simplified-aws-app-mesh-integration/
